// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      //windowでは使わないので、エラーを吐く
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpRSxaKbd8xgiSMlmdeXwISMa0t1AlHQ',
    appId: '1:64411265371:web:8f1c60280e987f8741527e',
    messagingSenderId: '64411265371',
    projectId: 'social-app-7084a',
    authDomain: 'social-app-7084a.firebaseapp.com',
    storageBucket: 'social-app-7084a.appspot.com',
    measurementId: 'G-LYH4H1RP0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcpSCTumhZ0_V7q91BZN9uh_Tfh4wvkTA',
    appId: '1:64411265371:android:ebfb437cca7e2e4d41527e',
    messagingSenderId: '64411265371',
    projectId: 'social-app-7084a',
    storageBucket: 'social-app-7084a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmykFr9ZfSeKmS5mObpUXbck1QQ4gCA-w',
    appId: '1:64411265371:ios:8d31335d787c6ed741527e',
    messagingSenderId: '64411265371',
    projectId: 'social-app-7084a',
    storageBucket: 'social-app-7084a.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmykFr9ZfSeKmS5mObpUXbck1QQ4gCA-w',
    appId: '1:64411265371:ios:82ed4a08d33af41a41527e',
    messagingSenderId: '64411265371',
    projectId: 'social-app-7084a',
    storageBucket: 'social-app-7084a.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
